name: nullsampler
description: "Um simples sampler 3x3 que te permite gravar sons à sua volta e fazer pequenos ritmos com eles"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
version: 0.1.0+1
environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  record: ^7.0.0
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
